from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
import os
import base64
from datetime import datetime
import json

from backend.database.sqlite_manager import sqlite_manager
from backend.database.duckdb_manager import duckdb_manager
from backend.agents.visualization_agent.chart_exporter import ChartExporter

# PDF and PPTX packages import
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.pdfgen import canvas
    
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    
    from docx import Document
    from docx.shared import Pt as DocxPt, Inches as DocxInches, RGBColor as DocxRGBColor
except Exception as e:
    print(f"Export dependencies warning: {e}")
    letter = None
    SimpleDocTemplate = None
    Presentation = None
    Document = None

router = APIRouter(
    tags=["Export"]
)


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor('#64748b'))
        
        # Header (Only on page 2 and later)
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor('#e2e8f0'))
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)
            self.drawString(36, 762, "AI Data Analytics Agent — Executive Report")
            self.drawRightString(576, 762, datetime.now().strftime('%Y-%m-%d'))
        
        # Footer (On all pages)
        self.setStrokeColor(colors.HexColor('#e2e8f0'))
        self.setLineWidth(0.5)
        self.line(36, 54, 576, 54)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(576, 40, page_text)
        self.drawString(36, 40, "Confidential • Generated by AI Data Analytics Agent")
        self.restoreState()


@router.get("/workspaces/{workspace_id}/export/pdf")
def export_pdf(workspace_id: int):
    ws = sqlite_manager.get_workspace(workspace_id)
    if not ws:
        raise HTTPException(status_code=404, detail="Workspace not found")

    if SimpleDocTemplate is None:
        raise HTTPException(status_code=500, detail="reportlab is not fully installed.")

    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"workspace_{workspace_id}.pdf")

    doc = SimpleDocTemplate(out_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=54, bottomMargin=54)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=15
    )
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#2563eb'),
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )
    code_style = ParagraphStyle(
        'DocCode',
        parent=styles['Code'],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0f172a'),
        backColor=colors.HexColor('#f1f5f9'),
        borderColor=colors.HexColor('#cbd5e1'),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=8
    )

    elements = []
    temp_images = []

    # 1. Cover / Metadata Section
    elements.append(Paragraph(f"Enterprise Analytics Report", title_style))
    elements.append(Paragraph(f"<b>Workspace:</b> {ws.get('name').upper()}", body_style))
    elements.append(Paragraph(f"<b>Dataset File:</b> {ws.get('file_name')}", body_style))
    elements.append(Paragraph(f"<b>Generated At:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", body_style))
    elements.append(Spacer(1, 15))

    # Dataset Summary Section
    elements.append(Paragraph("Dataset Profile Summary", section_style))
    meta = ws.get('metadata') or {}
    row_count = meta.get('row_count', 'N/A')
    col_count = meta.get('column_count', 'N/A')
    cols = meta.get('columns', [])
    elements.append(Paragraph(f"The dataset contains <b>{row_count}</b> rows and <b>{col_count}</b> columns.", body_style))
    elements.append(Paragraph(f"<b>Columns Profiled:</b> {', '.join(cols)}", body_style))
    elements.append(Spacer(1, 10))

    # Data Quality Summary
    elements.append(Paragraph("Data Cleaning Operations Log", section_style))
    cleaning_report = ws.get('cleaning_report') or {}
    report_desc = cleaning_report.get('report', 'No automated cleaning requested.')
    approved = "Yes" if ws.get('cleaning_approved') else "No (Pending User Confirmation)"
    elements.append(Paragraph(f"<b>Cleaning Actions Confirmed:</b> {approved}", body_style))
    elements.append(Paragraph(f"<b>Operation Logs:</b> {report_desc}", body_style))
    elements.append(Spacer(1, 15))

    # 2. Iterate Queries & Insights
    chats = sqlite_manager.get_chat_history(workspace_id)
    has_charts = False
    
    if chats:
        elements.append(Paragraph("AI-Generated Insights & Visualizations", section_style))
        for idx, chat in enumerate(chats):
            elements.append(Paragraph(f"<b>Analysis Request {idx + 1}:</b> {chat.get('question')}", body_style))
            if chat.get('sql_query'):
                elements.append(Paragraph(f"Generated SQL Query:", body_style))
                elements.append(Paragraph(chat.get('sql_query'), code_style))
            elements.append(Paragraph(f"<b>AI Insight:</b> {chat.get('answer')}", body_style))
            
            # Embed Chart if exists
            chart_json_str = chat.get('chart_json')
            result_json_str = chat.get('result_json')
            if chart_json_str and result_json_str:
                try:
                    chart_cfg = json.loads(chart_json_str)
                    result_data = json.loads(result_json_str)
                    
                    if result_data and chart_cfg:
                        rec = chart_cfg.get("recommendation", {})
                        c_type = rec.get("recommended", "bar")
                        x_col = rec.get("x")
                        y_col = rec.get("y")
                        
                        img_path = ChartExporter.generate_chart_image(
                            data_list=result_data,
                            chart_type=c_type,
                            x_col=x_col,
                            y_col=y_col
                        )
                        if img_path and os.path.exists(img_path):
                            temp_images.append(img_path)
                            elements.append(Spacer(1, 5))
                            elements.append(Image(img_path, width=420, height=252))
                            elements.append(Spacer(1, 10))
                            has_charts = True
                except Exception as ex:
                    print(f"Failed to embed chart in PDF: {ex}")
            elements.append(Spacer(1, 15))
    else:
        # Fallback dataset preview
        table_name = ws.get('table_name')
        if table_name:
            elements.append(Paragraph("Dataset Sample Preview (Top 10 Rows)", section_style))
            try:
                # Query table preview
                first_tbl = [t.strip() for t in table_name.split(",") if t.strip()][0]
                df = duckdb_manager.query(f"SELECT * FROM {first_tbl} LIMIT 10")
                data_list = [list(df.columns)]
                for _, row in df.iterrows():
                    data_list.append([str(val)[:15] for val in row])
                
                col_w = 540.0 / len(df.columns)
                col_widths = [col_w] * len(df.columns)
                t = Table(data_list, colWidths=col_widths)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 4),
                    ('TOPPADDING', (0,0), (-1,-1), 4),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.HexColor('#ffffff')])
                ]))
                elements.append(t)
            except Exception as e:
                elements.append(Paragraph(f"Could not load data preview: {e}", body_style))

    try:
        doc.build(elements, canvasmaker=NumberedCanvas)
        return FileResponse(out_path, media_type="application/pdf", filename=f"{ws.get('name')}_report.pdf")
    finally:
        # Clean up temp charts
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


@router.get("/workspaces/{workspace_id}/export/pptx")
def export_pptx(workspace_id: int):
    ws = sqlite_manager.get_workspace(workspace_id)
    if not ws:
        raise HTTPException(status_code=404, detail="Workspace not found")

    if Presentation is None:
        raise HTTPException(status_code=500, detail="python-pptx is not installed.")

    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"workspace_{workspace_id}.pptx")

    prs = Presentation()
    temp_images = []

    def apply_slide_title(slide, text):
        title = slide.shapes.title
        title.text = text
        for p in title.text_frame.paragraphs:
            p.font.size = Pt(28)
            p.font.bold = True
            p.font.color.rgb = RGBColor(30, 41, 59)

    # Slide 1: Cover Page
    slide1 = prs.slides.add_slide(prs.slide_layouts[0])
    slide1.shapes.title.text = ws.get('name').upper()
    slide1.placeholders[1].text = f"Business Intelligence Dashboard Report\nDataset: {ws.get('file_name')}\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

    # Slide 2: Dataset Profile & Quality
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    apply_slide_title(slide2, "Dataset Profile & Quality")
    tb2 = slide2.shapes.placeholders[1].text_frame
    meta = ws.get('metadata') or {}
    tb2.text = f"• Total Columns: {meta.get('column_count', 'N/A')}"
    tb2.add_paragraph().text = f"• Total Rows: {meta.get('row_count', 'N/A')}"
    cleaning_report = ws.get('cleaning_report') or {}
    report_desc = cleaning_report.get('report', 'No cleaning operations applied.')
    tb2.add_paragraph().text = f"• Cleaning Operations Log: {report_desc}"

    # Slide 3-N: Chats, Insights, and Charts
    chats = sqlite_manager.get_chat_history(workspace_id)
    if chats:
        for idx, chat in enumerate(chats[:5]): # Limit to top 5 queries for slides
            slide = prs.slides.add_slide(prs.slide_layouts[5]) # Blank with title
            apply_slide_title(slide, f"Query {idx + 1}: {chat.get('question')[:40]}...")
            
            # Left pane: SQL and Insight text
            left_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(5.0), Inches(5.0))
            tf = left_box.text_frame
            tf.word_wrap = True
            
            p_q = tf.paragraphs[0]
            p_q.text = f"Query: {chat.get('question')}"
            p_q.font.bold = True
            p_q.font.size = Pt(12)
            
            if chat.get('sql_query'):
                p_sql = tf.add_paragraph()
                p_sql.text = f"\nSQL:\n{chat.get('sql_query')}"
                p_sql.font.name = 'Courier New'
                p_sql.font.size = Pt(9)
                p_sql.font.color.rgb = RGBColor(100, 116, 139)
            
            p_ans = tf.add_paragraph()
            p_ans.text = f"\nAI Executive Insight:\n{chat.get('answer')}"
            p_ans.font.size = Pt(11)
            p_ans.font.color.rgb = RGBColor(51, 65, 85)

            # Right pane: Embed chart image if available
            chart_json_str = chat.get('chart_json')
            result_json_str = chat.get('result_json')
            if chart_json_str and result_json_str:
                try:
                    chart_cfg = json.loads(chart_json_str)
                    result_data = json.loads(result_json_str)
                    if result_data and chart_cfg:
                        rec = chart_cfg.get("recommendation", {})
                        c_type = rec.get("recommended", "bar")
                        x_col = rec.get("x")
                        y_col = rec.get("y")
                        
                        img_path = ChartExporter.generate_chart_image(
                            data_list=result_data,
                            chart_type=c_type,
                            x_col=x_col,
                            y_col=y_col
                        )
                        if img_path and os.path.exists(img_path):
                            temp_images.append(img_path)
                            slide.shapes.add_picture(img_path, Inches(5.8), Inches(1.5), Inches(3.8), Inches(4.5))
                except Exception as ex:
                    print(f"Failed to embed chart in pptx: {ex}")
    else:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        apply_slide_title(slide, "AI Analytics Insights")
        slide.shapes.placeholders[1].text_frame.text = "No questions have been run on this workspace yet. Execute a query to view slides."

    try:
        prs.save(out_path)
        return FileResponse(out_path, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", filename=f"{ws.get('name')}_presentation.pptx")
    finally:
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


@router.get("/workspaces/{workspace_id}/export/docx")
def export_docx(workspace_id: int):
    ws = sqlite_manager.get_workspace(workspace_id)
    if not ws:
        raise HTTPException(status_code=404, detail="Workspace not found")

    if Document is None:
        raise HTTPException(status_code=500, detail="python-docx package is not installed.")

    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"workspace_{workspace_id}.docx")

    doc = Document()
    temp_images = []

    # Title
    title = doc.add_heading(level=1)
    run = title.add_run("Executive Data Analysis Report")
    run.font.size = DocxPt(22)
    run.font.color.rgb = DocxRGBColor(30, 41, 59)

    doc.add_paragraph(f"Workspace Name: {ws.get('name').upper()}")
    doc.add_paragraph(f"Source Filename: {ws.get('file_name')}")
    doc.add_paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    doc.add_paragraph()

    # Meta Section
    h_meta = doc.add_heading("Dataset Overview", level=2)
    h_meta.runs[0].font.color.rgb = DocxRGBColor(37, 99, 235)
    meta = ws.get('metadata') or {}
    doc.add_paragraph(f"Total rows: {meta.get('row_count', 'N/A')}  |  Total columns: {meta.get('column_count', 'N/A')}")
    doc.add_paragraph(f"Columns schema: {', '.join(meta.get('columns', []))}")
    
    # Cleaning
    cleaning_report = ws.get('cleaning_report') or {}
    report_desc = cleaning_report.get('report', 'No issues cleaned.')
    doc.add_paragraph(f"Operations Log: {report_desc}")
    doc.add_paragraph()

    # Chats & Charts
    chats = sqlite_manager.get_chat_history(workspace_id)
    if chats:
        h_chats = doc.add_heading("Analytical Insights & Visualizations", level=2)
        h_chats.runs[0].font.color.rgb = DocxRGBColor(37, 99, 235)
        for idx, chat in enumerate(chats):
            p_q = doc.add_paragraph()
            r_q = p_q.add_run(f"Query {idx + 1}: {chat.get('question')}")
            r_q.bold = True
            
            if chat.get('sql_query'):
                p_sql = doc.add_paragraph()
                r_sql = p_sql.add_run(f"Generated SQL:\n{chat.get('sql_query')}")
                r_sql.font.name = 'Courier New'
                r_sql.font.size = DocxPt(9)
                r_sql.font.color.rgb = DocxRGBColor(100, 116, 139)

            p_ans = doc.add_paragraph()
            p_ans.add_run("AI Insight: ").bold = True
            p_ans.add_run(chat.get('answer'))

            chart_json_str = chat.get('chart_json')
            result_json_str = chat.get('result_json')
            if chart_json_str and result_json_str:
                try:
                    chart_cfg = json.loads(chart_json_str)
                    result_data = json.loads(result_json_str)
                    if result_data and chart_cfg:
                        rec = chart_cfg.get("recommendation", {})
                        c_type = rec.get("recommended", "bar")
                        x_col = rec.get("x")
                        y_col = rec.get("y")
                        
                        img_path = ChartExporter.generate_chart_image(
                            data_list=result_data,
                            chart_type=c_type,
                            x_col=x_col,
                            y_col=y_col
                        )
                        if img_path and os.path.exists(img_path):
                            temp_images.append(img_path)
                            doc.add_picture(img_path, width=DocxInches(5.0))
                            doc.add_paragraph()
                except Exception as ex:
                    print(f"Failed to embed chart in docx: {ex}")
            doc.add_paragraph("-" * 30)
    else:
        doc.add_paragraph("No questions have been run on this dataset yet.")

    try:
        doc.save(out_path)
        return FileResponse(out_path, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", filename=f"{ws.get('name')}_report.docx")
    finally:
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


@router.get("/workspaces/{workspace_id}/export/html")
def export_html(workspace_id: int):
    ws = sqlite_manager.get_workspace(workspace_id)
    if not ws:
        raise HTTPException(status_code=404, detail="Workspace not found")

    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"workspace_{workspace_id}.html")

    chats = sqlite_manager.get_chat_history(workspace_id)
    meta = ws.get('metadata') or {}
    cleaning_report = ws.get('cleaning_report') or {}

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Executive Data Report - {ws.get('name').upper()}</title>
    <style>
        body {{
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            color: #1e293b;
            background-color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
        }}
        .container {{
            max-width: 900px;
            margin: 0 auto;
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
            padding: 40px;
        }}
        .header {{
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #0f172a;
            margin: 0 0 10px 0;
            font-size: 28px;
        }}
        .meta-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            background: #f1f5f9;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}
        .meta-item h4 {{
            margin: 0 0 5px 0;
            color: #475569;
            font-size: 11px;
            text-transform: uppercase;
        }}
        .meta-item p {{
            margin: 0;
            font-weight: 600;
            font-size: 14px;
        }}
        h2 {{
            color: #2563eb;
            font-size: 18px;
            border-bottom: 1px solid #f1f5f9;
            padding-bottom: 8px;
            margin-top: 40px;
        }}
        .query-block {{
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 24px;
            margin-bottom: 24px;
        }}
        .query-block h3 {{
            margin: 0 0 12px 0;
            color: #0f172a;
            font-size: 15px;
        }}
        pre {{
            background: #0f172a;
            color: #e2e8f0;
            padding: 12px 16px;
            border-radius: 6px;
            font-size: 12px;
            overflow-x: auto;
            margin: 12px 0;
        }}
        .chart-img {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            border: 1px solid #e2e8f0;
            margin: 20px 0;
        }}
        .footer {{
            text-align: center;
            font-size: 12px;
            color: #64748b;
            margin-top: 50px;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Executive Data Analysis Report</h1>
            <p style="color: #64748b; margin: 0;">Automated Data Intelligence Output</p>
        </div>
        
        <div class="meta-grid">
            <div class="meta-item">
                <h4>Workspace Name</h4>
                <p>{ws.get('name').upper()}</p>
            </div>
            <div class="meta-item">
                <h4>Source File</h4>
                <p>{ws.get('file_name')}</p>
            </div>
            <div class="meta-item">
                <h4>Row/Col Dimension</h4>
                <p>{meta.get('row_count', 'N/A')} x {meta.get('column_count', 'N/A')}</p>
            </div>
            <div class="meta-item">
                <h4>Generated At</h4>
                <p>{datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
            </div>
        </div>

        <h2>Data Cleaning Operations Log</h2>
        <p style="font-size: 14px; line-height: 1.5;">{cleaning_report.get('report', 'No automated cleaning requested.')}</p>
        
        <h2>Analytical Insights & Visualizations</h2>
"""

    temp_images = []
    
    try:
        if chats:
            for idx, chat in enumerate(chats):
                chart_html = ""
                chart_json_str = chat.get('chart_json')
                result_json_str = chat.get('result_json')
                
                if chart_json_str and result_json_str:
                    try:
                        chart_cfg = json.loads(chart_json_str)
                        result_data = json.loads(result_json_str)
                        if result_data and chart_cfg:
                            rec = chart_cfg.get("recommendation", {})
                            c_type = rec.get("recommended", "bar")
                            x_col = rec.get("x")
                            y_col = rec.get("y")
                            
                            img_path = ChartExporter.generate_chart_image(
                                data_list=result_data,
                                chart_type=c_type,
                                x_col=x_col,
                                y_col=y_col
                            )
                            if img_path and os.path.exists(img_path):
                                temp_images.append(img_path)
                                with open(img_path, "rb") as image_file:
                                    encoded_string = base64.b64encode(image_file.read()).decode('utf-8')
                                chart_html = f'<img class="chart-img" src="data:image/png;base64,{encoded_string}" alt="Visual Chart" />'
                    except Exception as ex:
                        print(f"Failed to embed chart in html: {ex}")

                sql_html = f"<pre><code>{chat.get('sql_query')}</code></pre>" if chat.get('sql_query') else ""

                html_content += f"""
                <div class="query-block">
                    <h3>Request {idx + 1}: {chat.get('question')}</h3>
                    {sql_html}
                    <p><strong>AI Executive Insight:</strong> {chat.get('answer')}</p>
                    {chart_html}
                </div>
                """
        else:
            html_content += "<p>No questions have been run on this dataset yet.</p>"

        html_content += f"""
            <div class="footer">
                <p>Confidential • Generated by AI-Data-Analytics-Agent Platform</p>
            </div>
        </div>
    </body>
    </html>
    """

        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        return FileResponse(out_path, media_type="text/html", filename=f"{ws.get('name')}_report.html")
    finally:
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


from pydantic import BaseModel

class ExportReportRequest(BaseModel):
    include_dataset_summary: bool = True
    include_query_results: bool = True
    include_sql: bool = True
    include_insights: bool = True
    include_charts: bool = True
    include_tables: bool = True
    scope: str = "session"  # "current" or "session"
    format: str = "pdf"     # "pdf", "pptx", "excel"


@router.post("/workspaces/{workspace_id}/export_report")
def export_report_wizard(workspace_id: int, request: ExportReportRequest):
    ws = sqlite_manager.get_workspace(workspace_id)
    if not ws:
        raise HTTPException(status_code=404, detail="Workspace not found")
        
    chats = sqlite_manager.get_chat_history(workspace_id)
    if request.scope == "current":
        chats = chats[-1:] if chats else []
        
    out_dir = "exports"
    os.makedirs(out_dir, exist_ok=True)
    
    if request.format == "pdf":
        return generate_custom_pdf(ws, chats, request, workspace_id, out_dir)
    elif request.format == "pptx":
        return generate_custom_pptx(ws, chats, request, workspace_id, out_dir)
    elif request.format == "excel":
        return generate_custom_excel(ws, chats, request, workspace_id, out_dir)
    else:
        raise HTTPException(status_code=400, detail="Invalid format specified")


def generate_custom_pdf(ws, chats, request, workspace_id, out_dir):
    out_path = os.path.join(out_dir, f"custom_report_{workspace_id}.pdf")
    doc = SimpleDocTemplate(out_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=54, bottomMargin=54)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle', parent=styles['Heading1'], fontSize=24, leading=28, textColor=colors.HexColor('#0f172a'), alignment=1, spaceAfter=20
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle', parent=styles['Normal'], fontSize=11, leading=15, textColor=colors.HexColor('#475569'), alignment=1, spaceAfter=40
    )
    meta_style = ParagraphStyle(
        'MetaText', parent=styles['Normal'], fontSize=10, leading=14, textColor=colors.HexColor('#334155'), spaceAfter=8
    )
    section_style = ParagraphStyle(
        'SectionHeader', parent=styles['Heading2'], fontSize=14, leading=18, textColor=colors.HexColor('#2563eb'), spaceBefore=18, spaceAfter=8, keepWithNext=True
    )
    subsection_style = ParagraphStyle(
        'SubSectionHeader', parent=styles['Heading3'], fontSize=11, leading=14, textColor=colors.HexColor('#1e293b'), spaceBefore=10, spaceAfter=4, keepWithNext=True
    )
    body_style = ParagraphStyle(
        'DocBody', parent=styles['Normal'], fontSize=9, leading=13, textColor=colors.HexColor('#334155'), spaceAfter=6
    )
    code_style = ParagraphStyle(
        'DocCode', parent=styles['Code'], fontSize=8, leading=11, textColor=colors.HexColor('#0f172a'), backColor=colors.HexColor('#f8fafc'), borderColor=colors.HexColor('#e2e8f0'), borderWidth=0.5, borderPadding=8, spaceAfter=8
    )
    
    elements = []
    temp_images = []
    
    # 1. Title Page
    elements.append(Spacer(1, 150))
    elements.append(Paragraph("Executive Analytics Report", title_style))
    elements.append(Paragraph(f"Workspace: {ws.get('name').upper()}", subtitle_style))
    elements.append(Spacer(1, 80))
    elements.append(Paragraph(f"<b>Generated At:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", meta_style))
    elements.append(Paragraph(f"<b>Source Dataset:</b> {ws.get('file_name')}", meta_style))
    elements.append(Paragraph(f"<b>Generated by:</b> AI Data Analytics Agent", meta_style))
    elements.append(PageBreak())
    
    # 2. Dataset Information (if Include Dataset Summary is checked)
    if request.include_dataset_summary:
        elements.append(Paragraph("Dataset Information", section_style))
        meta = ws.get('metadata') or {}
        row_count = meta.get('row_count', 'N/A')
        col_count = meta.get('column_count', 'N/A')
        cols = meta.get('columns', [])
        elements.append(Paragraph(f"The workspace active dataset contains <b>{row_count}</b> rows and <b>{col_count}</b> columns.", body_style))
        elements.append(Paragraph(f"<b>Columns Profiled:</b> {', '.join(cols)}", body_style))
        
        # Cleaning summary info
        cleaning_report = ws.get('cleaning_report') or {}
        report_desc = cleaning_report.get('report', 'No automated cleaning requested.')
        elements.append(Paragraph("<b>Data Quality and Cleaning Logs:</b>", subsection_style))
        elements.append(Paragraph(report_desc, body_style))
        elements.append(Spacer(1, 15))
        
    # 3. Conversation History
    if chats:
        elements.append(Paragraph("Conversation History", section_style))
        for idx, chat in enumerate(chats):
            elements.append(Paragraph(f"<b>Request {idx + 1}:</b> {chat.get('question')}", subsection_style))
            elements.append(Paragraph(f"<b>Timestamp:</b> {chat.get('created_at', 'N/A')}", body_style))
            
            # Insights
            if request.include_insights:
                elements.append(Paragraph(f"<b>AI Insights:</b> {chat.get('answer')}", body_style))
                
            # SQL
            if request.include_sql and chat.get('sql_query'):
                elements.append(Paragraph("<b>Generated SQL:</b>", body_style))
                elements.append(Paragraph(chat.get('sql_query'), code_style))
                
            # Result Tables
            if request.include_tables and chat.get('result_json'):
                try:
                    result_data = json.loads(chat['result_json'])
                    if result_data:
                        # Build ReportLab table of first 10 rows and first 6 columns
                        cols_to_render = list(result_data[0].keys())[:6]
                        data_rows = [cols_to_render]
                        for r_item in result_data[:10]:
                            row_vals = []
                            for c_name in cols_to_render:
                                val = r_item.get(c_name)
                                row_vals.append(str(val)[:20] if val is not None else "")
                            data_rows.append(row_vals)
                            
                        col_width = 540.0 / len(cols_to_render)
                        col_widths = [col_width] * len(cols_to_render)
                        t = Table(data_rows, colWidths=col_widths)
                        t.setStyle(TableStyle([
                            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0f172a')),
                            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0,0), (-1,-1), 8),
                            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
                            ('TOPPADDING', (0,0), (-1,-1), 4),
                            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
                            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#f8fafc'), colors.HexColor('#ffffff')])
                        ]))
                        elements.append(Spacer(1, 4))
                        elements.append(t)
                        elements.append(Spacer(1, 6))
                except Exception as ex:
                    print(f"Table render error: {ex}")
                    
            # Visualizations (Charts)
            if request.include_charts and chat.get('chart_json') and chat.get('result_json'):
                try:
                    chart_cfg = json.loads(chat['chart_json'])
                    result_data = json.loads(chat['result_json'])
                    if result_data and chart_cfg:
                        rec = chart_cfg.get("recommendation", {})
                        c_type = rec.get("recommended", "bar")
                        x_col = rec.get("x")
                        y_col = rec.get("y")
                        
                        img_path = ChartExporter.generate_chart_image(
                            data_list=result_data,
                            chart_type=c_type,
                            x_col=x_col,
                            y_col=y_col
                        )
                        if img_path and os.path.exists(img_path):
                            temp_images.append(img_path)
                            elements.append(Spacer(1, 6))
                            elements.append(Image(img_path, width=400, height=240))
                            elements.append(Spacer(1, 8))
                except Exception as ex:
                    print(f"Chart render error: {ex}")
                    
            elements.append(Spacer(1, 15))
            
    # 4. Summary & End notes
    elements.append(Paragraph("Executive Summary", section_style))
    elements.append(Paragraph(f"This analytics report contains a detailed breakdown of {len(chats)} queries executed on the workspace dataset. The information presented was auto-generated by the AI Data Analytics Agent.", body_style))
    elements.append(Spacer(1, 25))
    elements.append(Paragraph(f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", meta_style))
    
    # Save Report details to database
    report_title = f"{ws.get('name').upper()} Wizard Report ({request.scope.upper()})"
    sqlite_manager.create_report(workspace_id, report_title, out_path, "pdf")
    
    try:
        doc.build(elements, canvasmaker=NumberedCanvas)
        return FileResponse(out_path, media_type="application/pdf", filename=f"{ws.get('name')}_custom_report.pdf")
    finally:
        # Clean up temp charts
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


def generate_custom_pptx(ws, chats, request, workspace_id, out_dir):
    out_path = os.path.join(out_dir, f"custom_report_{workspace_id}.pptx")
    prs = Presentation()
    temp_images = []
    
    def apply_slide_title(slide, text):
        title = slide.shapes.title
        title.text = text
        for p in title.text_frame.paragraphs:
            p.font.size = Pt(24)
            p.font.bold = True
            p.font.color.rgb = RGBColor(15, 23, 42)
            
    # Slide 1: Cover Page
    slide_layout = prs.slide_layouts[0]
    slide1 = prs.slides.add_slide(slide_layout)
    slide1.shapes.title.text = ws.get('name').upper()
    slide1.placeholders[1].text = f"Custom Business Intelligence Report\nScope: {request.scope.capitalize()}\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    
    # Slide 2: Dataset summary
    if request.include_dataset_summary:
        slide_layout = prs.slide_layouts[1]
        slide2 = prs.slides.add_slide(slide_layout)
        apply_slide_title(slide2, "Dataset Overview Summary")
        tb = slide2.shapes.placeholders[1].text_frame
        meta = ws.get('metadata') or {}
        tb.text = f"• Dataset File: {ws.get('file_name')}"
        tb.add_paragraph().text = f"• Total Columns: {meta.get('column_count', 'N/A')}"
        tb.add_paragraph().text = f"• Total Rows: {meta.get('row_count', 'N/A')}"
        cleaning = ws.get('cleaning_report') or {}
        tb.add_paragraph().text = f"• Data Operations Log: {cleaning.get('report', 'No issues cleaned.')}"
        
    # Slide 3-N: Chat conversations
    for idx, chat in enumerate(chats):
        # Slide A: Question, SQL, Insights
        slide_layout = prs.slide_layouts[5] # blank with title
        slide_a = prs.slides.add_slide(slide_layout)
        apply_slide_title(slide_a, f"Query {idx + 1}: {chat.get('question')[:40]}...")
        
        tb_a = slide_a.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(9.0), Inches(5.3))
        tf = tb_a.text_frame
        tf.word_wrap = True
        
        p_q = tf.paragraphs[0]
        p_q.text = f"Question: {chat.get('question')}"
        p_q.font.bold = True
        p_q.font.size = Pt(14)
        p_q.font.color.rgb = RGBColor(37, 99, 235)
        
        if request.include_sql and chat.get('sql_query'):
            p_sql = tf.add_paragraph()
            p_sql.text = f"\nGenerated SQL Query:\n{chat.get('sql_query')}"
            p_sql.font.name = 'Courier New'
            p_sql.font.size = Pt(10)
            p_sql.font.color.rgb = RGBColor(71, 85, 105)
            
        if request.include_insights and chat.get('answer'):
            p_ans = tf.add_paragraph()
            p_ans.text = f"\nAI Executive Insight:\n{chat.get('answer')}"
            p_ans.font.size = Pt(11)
            p_ans.font.color.rgb = RGBColor(15, 23, 42)
            
        # Slide B: Table and Chart (if both/either is selected)
        if (request.include_tables and chat.get('result_json')) or (request.include_charts and chat.get('chart_json')):
            slide_b = prs.slides.add_slide(prs.slide_layouts[5])
            apply_slide_title(slide_b, f"Results & Visuals for Query {idx + 1}")
            
            # Left side: Table (first 8 rows, first 4 columns to fit)
            if request.include_tables and chat.get('result_json'):
                try:
                    result_data = json.loads(chat['result_json'])
                    if result_data:
                        cols_to_render = list(result_data[0].keys())[:4]
                        rows_to_render = result_data[:8]
                        
                        rows_cnt = len(rows_to_render) + 1
                        cols_cnt = len(cols_to_render)
                        
                        # Add table (x, y, cx, cy)
                        left_pos = Inches(0.5)
                        top_pos = Inches(1.5)
                        width_pos = Inches(4.5)
                        height_pos = Inches(4.5)
                        
                        tbl_shape = slide_b.shapes.add_table(rows_cnt, cols_cnt, left_pos, top_pos, width_pos, height_pos)
                        table = tbl_shape.table
                        
                        # Header
                        for c_idx, c_name in enumerate(cols_to_render):
                            cell = table.cell(0, c_idx)
                            cell.text = str(c_name)
                            cell.fill.solid()
                            cell.fill.fore_color.rgb = RGBColor(15, 23, 42)
                            cell.text_frame.paragraphs[0].font.color.rgb = RGBColor(255, 255, 255)
                            cell.text_frame.paragraphs[0].font.size = Pt(10)
                            
                        # Rows
                        for r_idx, r_item in enumerate(rows_to_render):
                            for c_idx, c_name in enumerate(cols_to_render):
                                cell = table.cell(r_idx + 1, c_idx)
                                cell.text = str(r_item.get(c_name, ""))[:15]
                                cell.text_frame.paragraphs[0].font.size = Pt(9)
                except Exception as ex:
                    print(f"PPTX Table render error: {ex}")
                    
            # Right side: Chart image
            if request.include_charts and chat.get('chart_json') and chat.get('result_json'):
                try:
                    chart_cfg = json.loads(chat['chart_json'])
                    result_data = json.loads(chat['result_json'])
                    if result_data and chart_cfg:
                        rec = chart_cfg.get("recommendation", {})
                        c_type = rec.get("recommended", "bar")
                        x_col = rec.get("x")
                        y_col = rec.get("y")
                        
                        img_path = ChartExporter.generate_chart_image(
                            data_list=result_data,
                            chart_type=c_type,
                            x_col=x_col,
                            y_col=y_col
                        )
                        if img_path and os.path.exists(img_path):
                            temp_images.append(img_path)
                            left_c = Inches(5.2) if request.include_tables else Inches(2.0)
                            width_c = Inches(4.3) if request.include_tables else Inches(6.0)
                            slide_b.shapes.add_picture(img_path, left_c, Inches(1.5), width_c, Inches(4.5))
                except Exception as ex:
                    print(f"PPTX Chart render error: {ex}")
                    
    # Save Presentation Report details to database
    report_title = f"{ws.get('name').upper()} Wizard Presentation ({request.scope.upper()})"
    sqlite_manager.create_report(workspace_id, report_title, out_path, "pptx")
    
    try:
        prs.save(out_path)
        return FileResponse(out_path, media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", filename=f"{ws.get('name')}_custom_presentation.pptx")
    finally:
        for img in temp_images:
            if os.path.exists(img):
                try:
                    os.remove(img)
                except OSError:
                    pass


import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

def generate_custom_excel(ws, chats, request, workspace_id, out_dir):
    out_path = os.path.join(out_dir, f"custom_report_{workspace_id}.xlsx")
    wb = openpyxl.Workbook()
    
    # Fonts and styles
    title_font = Font(name='Segoe UI', size=14, bold=True, color='1E293B')
    header_font = Font(name='Segoe UI', size=11, bold=True, color='FFFFFF')
    bold_font = Font(name='Segoe UI', size=10, bold=True, color='334155')
    regular_font = Font(name='Segoe UI', size=10, color='334155')
    mono_font = Font(name='Consolas', size=9, color='475569')
    
    header_fill = PatternFill(start_color='0F172A', end_color='0F172A', fill_type='solid')
    
    border_side = Side(border_style='thin', color='E2E8F0')
    border_all = Border(left=border_side, right=border_side, top=border_side, bottom=border_side)
    
    # 1. Summary Sheet
    ws_summary = wb.active
    ws_summary.title = "Summary"
    ws_summary.views.sheetView[0].showGridLines = True
    
    ws_summary['A1'] = "Enterprise Data Analytics Report"
    ws_summary['A1'].font = title_font
    
    ws_summary['A3'] = "Workspace Display Name:"
    ws_summary['A3'].font = bold_font
    ws_summary['B3'] = ws.get('name').upper()
    ws_summary['B3'].font = regular_font
    
    ws_summary['A4'] = "Source File:"
    ws_summary['A4'].font = bold_font
    ws_summary['B4'] = ws.get('file_name')
    ws_summary['B4'].font = regular_font
    
    ws_summary['A5'] = "Generated At:"
    ws_summary['A5'].font = bold_font
    ws_summary['B5'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    ws_summary['B5'].font = regular_font
    
    if request.include_dataset_summary:
        meta = ws.get('metadata') or {}
        ws_summary['A7'] = "Dataset Summary"
        ws_summary['A7'].font = Font(name='Segoe UI', size=12, bold=True, color='2563EB')
        
        ws_summary['A9'] = "Total Rows:"
        ws_summary['A9'].font = bold_font
        ws_summary['B9'] = meta.get('row_count', 'N/A')
        ws_summary['B9'].font = regular_font
        
        ws_summary['A10'] = "Total Columns:"
        ws_summary['A10'].font = bold_font
        ws_summary['B10'] = meta.get('column_count', 'N/A')
        ws_summary['B10'].font = regular_font
        
        ws_summary['A11'] = "Columns Profiled:"
        ws_summary['A11'].font = bold_font
        ws_summary['B11'] = ', '.join(meta.get('columns', []))
        ws_summary['B11'].font = regular_font
        
        cleaning = ws.get('cleaning_report') or {}
        ws_summary['A13'] = "Data Cleaning Logs:"
        ws_summary['A13'].font = bold_font
        ws_summary['B13'] = cleaning.get('report', 'No automated cleaning requested.')
        ws_summary['B13'].font = regular_font
        
    # 2. Add sheet for each query result
    for idx, chat in enumerate(chats):
        sheet_title = f"Query {idx + 1}"
        ws_q = wb.create_sheet(title=sheet_title)
        ws_q.views.sheetView[0].showGridLines = True
        
        # Meta info of query at top
        ws_q['A1'] = f"Request {idx + 1} Metadata"
        ws_q['A1'].font = Font(name='Segoe UI', size=12, bold=True, color='2563EB')
        
        ws_q['A3'] = "Question:"
        ws_q['A3'].font = bold_font
        ws_q['B3'] = chat.get('question')
        ws_q['B3'].font = regular_font
        
        ws_q['A4'] = "Timestamp:"
        ws_q['A4'].font = bold_font
        ws_q['B4'] = chat.get('created_at', 'N/A')
        ws_q['B4'].font = regular_font
        
        row_offset = 6
        
        if request.include_insights and chat.get('answer'):
            ws_q[f'A{row_offset}'] = "AI Insight:"
            ws_q[f'A{row_offset}'].font = bold_font
            ws_q[f'B{row_offset}'] = chat.get('answer')
            ws_q[f'B{row_offset}'].font = regular_font
            row_offset += 2
            
        if request.include_sql and chat.get('sql_query'):
            ws_q[f'A{row_offset}'] = "Generated SQL:"
            ws_q[f'A{row_offset}'].font = bold_font
            ws_q[f'B{row_offset}'] = chat.get('sql_query')
            ws_q[f'B{row_offset}'].font = mono_font
            row_offset += 2
            
        # Add result table
        if request.include_tables and chat.get('result_json'):
            try:
                result_data = json.loads(chat['result_json'])
                if result_data:
                    ws_q[f'A{row_offset}'] = "QueryResult Table"
                    ws_q[f'A{row_offset}'].font = Font(name='Segoe UI', size=11, bold=True, color='0F172A')
                    row_offset += 1
                    
                    headers = list(result_data[0].keys())
                    
                    # Headers row
                    for c_idx, h_name in enumerate(headers):
                        col_cell = ws_q.cell(row=row_offset, column=c_idx + 1)
                        col_cell.value = h_name
                        col_cell.font = header_font
                        col_cell.fill = header_fill
                        col_cell.alignment = Alignment(horizontal='center')
                        
                    row_offset += 1
                    
                    # Values rows
                    for r_item in result_data:
                        for c_idx, h_name in enumerate(headers):
                            val_cell = ws_q.cell(row=row_offset, column=c_idx + 1)
                            val_cell.value = r_item.get(h_name)
                            val_cell.font = regular_font
                            val_cell.border = border_all
                        row_offset += 1
            except Exception as ex:
                print(f"Excel Table render error: {ex}")
                
        # Auto-fit columns
        for col in ws_q.columns:
            max_len = 0
            col_letter = col[0].column_letter
            for cell in col:
                if cell.value:
                    max_len = max(max_len, len(str(cell.value)))
            ws_q.column_dimensions[col_letter].width = min(max(max_len + 3, 10), 50)
            
    wb.save(out_path)
    
    # Save Report details to database
    report_title = f"{ws.get('name').upper()} Wizard Excel ({request.scope.upper()})"
    sqlite_manager.create_report(workspace_id, report_title, out_path, "excel")
    
    return FileResponse(out_path, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename=f"{ws.get('name')}_custom_data.xlsx")
